# Generated by Django 6.0.3 on 2026-04-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
